version: "3.7"
services:
  testapp:
    depends_on:
      - postgres
      # - mysql
    build:
      context: ./
      dockerfile: ./Dockerfile
      target: test
    environment:
      DEBUG: "True"
      POSTGRESQL_URL: postgresql://postgres:password@postgres:5432/testapp
    volumes:
      - ./:/opt/sqly

  # mysql:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: testapp
  #     MYSQL_USER: testapp
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /var/lib/mysql:/var/lib/mysql

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: testapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .:/code

volumes:
  pgdata:
